### ISSUE TITLE
Crash when used in conjunction with "what is it really used for" mod.

### ISSUE THREAD

**Issue by TheCadde** [SereneRebel/factorio_plc#2] opened 2018-11-01 17:02 UTC
`__plc__/control.lua:440: attempt to index field '?' (a nil value)`

The variable `global.gui[event.player_index]` can sometimes be nil for some reason.

The way i reproduced it on my save was to plop down the PLC, mess about a bit, mine it and then much later i opened "what is it really used for" search box, typed in "crushed" and clicked "crushed stiratite" (but i doubt it matters what you pick) and then when one presses escape, the above error happens.

I fixed it locally by adding another check.

`if global.gui.open and global.gui[event.player_index] and global.gui[event.player_index].main == event.element then`

**Comment by SereneRebel** [comment] 2019-01-05 08:41
It seems like one of those corner cases caused by "something" and yes it should have a nil check. thanks for the feedback.

when i get a moment i shall fix this up

**Comment by SereneRebel** [comment] 2024-02-19 09:46
Fixed in latest version

**Closed as completed** 2024-02-19 09:47 UTC
Labels: bug, next release
